# Generated by Django 3.1.4 on 2021-02-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_likes2'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=2, max_length=1500)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
