# Generated by Django 3.1.4 on 2021-02-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210216_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default=2, max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
